INFO:Slither:Compilation warnings/errors on /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol:
Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol:793:9:
    |
793 |         address _tokenIn,
    |         ^^^^^^^^^^^^^^^^

Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol:795:9:
    |
795 |         uint256 _minAmountOut,
    |         ^^^^^^^^^^^^^^^^^^^^^

Warning: Function state mutability can be restricted to pure
   --> /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol:742:5:
    |
742 |     function scaleTo(uint256 _amount, uint256 _decimal) internal returns (uint256) {
    |     ^ (Relevant source part starts here and spans across multiple lines).

Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
   --> /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol:228:1:
    |
228 | contract ProxyActions {
    | ^ (Relevant source part starts here and spans across multiple lines).


ERROR:root:Error in /sb/0x6f0b967a8200c764d09a781397a28f0a0ec259c0.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/__main__.py", line 564, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/__main__.py", line 53, in process
    triage_mode=args.triage_mode)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/slither.py", line 58, in __init__
    self._analyze_contracts()
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 249, in _analyze_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 311, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/slitherSolc.py", line 355, in _analyze_struct_events
    contract.analyze_structs()
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/declarations/contract.py", line 411, in analyze_structs
    self._analyze_struct(struct)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/declarations/contract.py", line 407, in _analyze_struct
    struct.analyze()
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/declarations/structure.py", line 24, in analyze
    elem = StructureVariableSolc(elem_to_parse)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.1-py3.6.egg/slither/solc_parsing/variables/variable_declaration.py", line 52, in __init__
    self._init_from_declaration(var, var['value'])
KeyError: 'value'

